name: Github Actions CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"
      - run: npm install
      - run: npm install -g codecov
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"
      - run: npm run lint
      - run: npm run pretty
      - run: npm run test
      - run: npm run coverage
