name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"
      - run: npm install
      - run: npm -g codecov
      - name: Lints Code
      - run: npm run lint
      - name: Runs tests
      - run: npm run test
      - name: Runs Coverage
      - run: npm run coverage
      - name: Generates CodeCov
      - run: codecov
